### ISSUE TITLE
Display types of events in the wiki

### ISSUE THREAD

**Issue by Tigerfell** [thomersch/OSMCALWikiWidget#1]
The current calendar system indicates the kind of an event by using specific symbols. It would be helpful if the extension would show this, too.

**Comment by thomersch** [comment]
The event types are not something I want to support, because they cause confusion for many event creators and don‘t really communicate the purpose of the event for the consumers. Often there are event, which have the same nature, but use wildly different categories (e.g. meet vs pub).

I have a replacement system in my mind (and partially in code), but that is going to take a while.
